@startuml

package com.example.zootypers {

  class TitlePage {
    -Activity activity
    +void onCreate(Bundle)
    +void onCreateOptionsMenu(Menu) : boolean
    +void goToPreGameSelection(View)
    +void goToPreGameSelectionMulti(View)
    +void goToLeaderboard(View)
    +void goToOptions(View)
    +void onBackPressed()
  }

  class PreGameSelection {
    -int HIGHTLIGHT_COLOR = 0xFF000000
    -View diff
    -View animal
    -View background
    +void onCreate(Bundle)
    +void onCreateOptionsMenu(Menu) : boolean
    +void setDiff(View)
    +void setAnimal(View)
    +void setBackground(View)
    +void goToSinglePlayer(View)
    +void goToTitlePage(View)
    +void onBackPressed()
  }

  class SinglePlayer {
    -SinglePlayerModel model
    -int NUM_WORDS = 5
    -int bg
    -PopupWindow ppw
    -long currentTime
    -long pausedTime
    -GameTimer gameTimer
    +void onCreate(Bundle)
    +void onCreateOptionsMenu(Menu) : boolean
    +boolean onKeyDown(int, KeyEvent) : boolean
    +void onPause()
    +void initialDisplay(Drawable, Drawable)
    +void displayWord(int, String)
    +void displayTime(long)
    +void displayScore(int)
    +void highlightWord(int, String, int)
    +void update(Observable, Object)
    +void keyboardButton(View)
    +void goToPostGame()
    +View getByStringId(String) : View
    +void pauseGame(View)
    +void pausedContinue(View)
    +void pausedNewGame(View)
    +void pausedMainMenu(View)
  }

  class SinglePlayerModel {
    -int numWordsDisplayed
    -String[] wordsList
    -int[] wordsDisplayed
    -int currWordIndex
    -int currLetterIndex
    -int nextWordIndex
    -int score
    -AssetManager am
    -Set<Character> currFirstLetters
    +void populateDisplayedList()
    +void typedLetter(char)
    +int getScore() : int
    +String getCurrWord() : String
    +int getCurrWordIndex() : int
    +int getCurrLetterIndex() : int
  }

  class PostGameScreen {
    +void onCreate(Bundle)
    +void onBackPressed()
    +void onCreateOptionsMenu(Menu) : boolean
    +void goToTitlePage(View)
    +void goToPreGameSelection(View)
  }

}

@enduml
